version: '3'

services:
  backend:
    build:
      context: .
    container_name: backend_container
    ports:
      - 8000:8000
    # command: >
    #   sh -c "python3 manage.py makemigrations &&
    #          python manage.py migrate &&
    #          python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend/
    container_name: frontend_container
    ports:
      - 5000:5000  # Map container port 5000 to host port 5000
